apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
#  googleCloudBuild:
#    projectId: microservice-showcase
  artifacts:
#   GOOGLE CLOUD SKD SETUP
#   US.GCR.IO/<PROJECTID>/<IMAGE NAME>
#   - image: us.gcr.io/microservice-showcase/auth
    - image: zjayers/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
