name: deploy-orders
on:
  push:
    branches:
      - master
    paths:
      - 'service.orders/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd service.orders && docker build -t zjayers/orders .
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push zjayers/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_KEY }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-depl