name: tests-orders

on:
  pull_request:
    paths:
      - 'service.orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd service.orders && npm install && npm run test:ci

