name: tests-payments

on:
  pull_request:
    paths:
      - 'service.payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd service.payments && npm install && npm run test:ci
        env: # Or as an environment variable
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}

