name: tests-payments

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd service.payments && npm install && npm run test:ci
        env: # Or as an environment variable
          super_secret: ${{ secrets.STRIPE_SECRET }}

